export PATH=$PATH:/usr/local/mysql/bin/
PS1='\n\D{%Y-%m-%d %H:%M:%S}\n$PWD\n[ \u @ \H ]\$ '

alias                             l='ls -l'
alias                             q='ls | less'
alias                           cls='clear'
alias                           cla='clear && ls -al'
alias                            cl='clear && ls -l'
alias                            lc='clear && ls -l'
alias                           cll='clear && ls'
alias                           clt='clear && ls -l --sort=time'
alias                           csl='clear'
alias                           lsc='clear'
alias                           lcs='clear'
alias                            ll='ls -alF'
alias                            la='ls -al'
alias                            lg='ls -og'
alias                           clg='clear && ls -g'
alias                            lf='ls -f -l'
alias                            lt='ls -l --sort=time'
alias                            rm='rm -i'
alias                            rd='rm -rf -i'
alias                            cp='cp -i'
alias                            mv='mv -i'
alias                          hcls='cat /dev/null > ~/.bash_history && history -c'
alias                         mytar='tar -zxvf'
                                   
alias                       cpuinfo='cat /proc/cpuinfo && sensors'
alias                      ipconfig='ifconfig | grep "Bcast" | grep "inet addr"'

alias                      findfile='find . -name'
alias                            ft='find . -name "*.txt"'
alias                           ftr='find . -name "*.txt" -exec rm -f {} \;'
alias                       rmosxds='find . -name ".DS_Store" -exec rm -rf {} \;'
alias                     rmosxicon='find . -name "Icon" -exec rm -rf {} \; && find . -name "Icon?" -exec rm -rf {} \;'
alias                       cdtpphc='cd ~/Dropbox/TPPHC'
alias                            im='vim'
alias                           vom='vim'
alias                           bim='vim'
alias                            ii='touch i && vim i'
alias                           iii='/bin/sh i'
                                   
alias                            tv='cat ~/Dropbox/misc/tv.info.txt && echo '
alias                  cloudcompare='cloudcompare.CloudCompare &'
                                   
alias                            dk='docker'
alias                           dki='docker images'
alias                          dkps='docker ps'
alias                         dkpsa='docker ps -a'
alias                        dkpsaq='docker ps -a -q'
alias                         dkrdt='docker run -d -t'
alias                         dkrit='docker run -i -t'
alias                     dkrminone='docker rmi -f $(dki -f "dangling=true" -q)'
alias                        dkstop='docker stop --time=1'
                                   
alias                          pika='docker exec -it sleepy_pikachu bash'
alias                       monpika='docker exec -it sleepy_pikachu tail -f /status'
alias                         pichu='docker exec -it sleepy_pichu bash'
alias                      monpichu='docker exec -it sleepy_pichu tail -f /status'
alias                       jirachi='docker exec -it sleepy_jirachi bash'
alias                   opendatalab='google-chrome http://localhost:9999'
alias                           odl='google-chrome http://localhost:9999/lab/workspaces/pikachu' # '/usr/bin/google-chrome-stable https://localhost:9999/lab/workspaces/pikachu'
                                   
alias                             p='python'
alias                            py='python'
alias                            yp='python'
alias                           py3='python3'
alias                           yp3='python3'
alias               pip-upgrade-all='pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U'
alias              pip3-upgrade-all='pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U'
alias                            sl='ls'
alias                            yd='youtube-dl'
alias                         ydmp3='youtube-dl -x --audio-format mp3' #source : www.tecmint.com/download-mp3-track-from-yuoutube-video-using-youtube-dl/
                                   
alias                      baretail='tail -f'
alias                      killtask='kill -9 '
                                   
alias                        scihub='google-chrome http://sci-hub.tw/'
alias                          gits='git status'
alias                          gitb='git branch'
alias                          gitd='git diff'
alias                          gita='git add'
alias                          gitf='git fetch'
alias                          gitr='git reset'
alias                          gitc='git checkout'
alias                        gitamu='git add .; git commit -m "update"; git push'
#alias                       githist='git log --pretty=format:"%h %s" --graph'
alias                       githist='git log --graph --oneline --decorate --color'
alias                   gitmanmerge='git merge --no-commit --no-ff'
alias             gitfetchallbranch='git branch -r | grep -v ''\->'' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done'

alias                       aipmail='google-chrome https://privateemail.com/appsuite' # pw is 2alphabet + 6digit
alias                       mingdao='google-chrome https://www.mingdao.com/home' # pw is 2alphabet + 6digit
alias                      electron='~/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'
alias                     googlecal='google-chrome https://calendar.google.com/calendar/r'
alias                          gcal='googlecal'
alias                            go='google-chrome https://www.cosumi.net/en'
alias                      viewlive='google-chrome https://ncehk2019.github.io/nce-live/'

alias                      loopdush='while true ; do clear ; date ; du -sh * ; sleep 1 ; done'
alias                       loopdus='while true ; do clear ; date ; du -s * ; sleep 1 ; done'

